
http://localhost:4000/
###
http://localhost:4000/status
###
http://localhost:3000/blocks
###
POST http://localhost:3000/blocks
###
POST http://localhost:3000/transactions

{
    "to":"Woo",
    "amount":10
}
###
http://localhost:3000/mempool
###
http://localhost:4000/balance/Woo

###
POST http://localhost:4000/peers

{
    "address": "127.0.0.1",
    "port": "2000"
}
###
http://localhost:2000/peers
###
POST http://localhost:3000/pay_Tax

{
    "to":"Government",
    "Amount":389917
}